git clone https://github.com/decentraland/account.git
git clone https://github.com/decentraland/actions.git
git clone https://github.com/decentraland/add-mana.git
git clone https://github.com/decentraland/adr.git
git clone https://github.com/decentraland/actix-web-prom.git
git clone https://github.com/decentraland/agora.git
git clone https://github.com/decentraland/aragonswap.git
git clone https://github.com/decentraland/archipelago-nats.git
git clone https://github.com/decentraland/archipelago-prometheus-nats-exporter.git
git clone https://github.com/decentraland/archipelago-workers.git
git clone https://github.com/decentraland/architecture.git
git clone https://github.com/decentraland/artweek.git
git clone https://github.com/decentraland/asset-bundle-converter.git
git clone https://github.com/decentraland/asset-packs.git
git clone https://github.com/decentraland/automated-webgl-test.git
git clone https://github.com/decentraland/aux-contracts.git
git clone https://github.com/decentraland/block-indexer.git
git clone https://github.com/decentraland/auth-server.git
git clone https://github.com/decentraland/avatar-asset-test-tool.git
git clone https://github.com/decentraland/avatars-contract.git
git clone https://github.com/decentraland/base-ts-project.git
git clone https://github.com/decentraland/bevy-explorer.git
git clone https://github.com/decentraland/bid-contract.git
git clone https://github.com/decentraland/avatar-assets.git
git clone https://github.com/decentraland/atlas-server.git
git clone https://github.com/decentraland/auction.git
git clone https://github.com/decentraland/auth-go.git
git clone https://github.com/decentraland/auth.git
git clone https://github.com/decentraland/bounties.git
git clone https://github.com/decentraland/bronzeage-node.git
git clone https://github.com/decentraland/builder.git
git clone https://github.com/decentraland/builder-assets.git
git clone https://github.com/decentraland/builder-client.git
git clone https://github.com/decentraland/builder-server.git
git clone https://github.com/decentraland/builder-templates.git
git clone https://github.com/decentraland/camera-reel-service.git
git clone https://github.com/decentraland/canilla.git
git clone https://github.com/decentraland/casi-hackers-hackaton.git
git clone https://github.com/decentraland/cast.git
git clone https://github.com/decentraland/catalyst-api-specs.git
git clone https://github.com/decentraland/bronzeage-editor.git
git clone https://github.com/decentraland/calculate-populated-land.git
git clone https://github.com/decentraland/catalyst.git
git clone https://github.com/decentraland/catalyst-client.git
git clone https://github.com/decentraland/catalyst-client-examples.git
git clone https://github.com/decentraland/catalyst-comms-peer.git
git clone https://github.com/decentraland/catalyst-contracts.git
git clone https://github.com/decentraland/catalyst-monitor.git
git clone https://github.com/decentraland/catalyst-owner.git
git clone https://github.com/decentraland/catalyst-run.git
git clone https://github.com/decentraland/catalyst-stats.git
git clone https://github.com/decentraland/catalyst-storage.git
git clone https://github.com/decentraland/checker-contract.git
git clone https://github.com/decentraland/ClearScript.git
git clone https://github.com/decentraland/cli.git
git clone https://github.com/decentraland/cli-e2e.git
git clone https://github.com/decentraland/cli-preview-in-server.git
git clone https://github.com/decentraland/client-sdk-unity.git
git clone https://github.com/decentraland/collaborative-editor-server.git
git clone https://github.com/decentraland/collection-proxy-verifier.git
git clone https://github.com/decentraland/collections-graph.git
git clone https://github.com/decentraland/common-contracts.git
git clone https://github.com/decentraland/comms-gatekeeper.git
git clone https://github.com/decentraland/comms-library.git
git clone https://github.com/decentraland/comms-station.git
git clone https://github.com/decentraland/comms-v3.git
git clone https://github.com/decentraland/comms3-livekit-transport.git
git clone https://github.com/decentraland/communications-protocol.git
git clone https://github.com/decentraland/communications-server.git
git clone https://github.com/decentraland/content-hash-tree.git
git clone https://github.com/decentraland/content-service.git
git clone https://github.com/decentraland/content-validator.git
git clone https://github.com/decentraland/contracts.git
git clone https://github.com/decentraland/contracts-plugins.git
git clone https://github.com/decentraland/crashbot.git
git clone https://github.com/decentraland/crunch.git
git clone https://github.com/decentraland/dae-unit-tests.git
git clone https://github.com/decentraland/dao-apps.git
git clone https://github.com/decentraland/dao-curations-calc.git
git clone https://github.com/decentraland/dao-scenes-ranking.git
git clone https://github.com/decentraland/dapp-boilerplate.git
git clone https://github.com/decentraland/dappeteer.git
git clone https://github.com/decentraland/dapps-issues.git
git clone https://github.com/decentraland/dcl-builder-hud.git
git clone https://github.com/decentraland/dcl-crypto-middleware-rs.git
git clone https://github.com/decentraland/dcl-crypto-toolkit.git
git clone https://github.com/decentraland/dcl-access-area.git
git clone https://github.com/decentraland/dcl-ecs-quests.git
git clone https://github.com/decentraland/dcl-deploy-action.git
git clone https://github.com/decentraland/dcl-gin.git
git clone https://github.com/decentraland/dcl-godot-cli.git
git clone https://github.com/decentraland/dcl-http-prom-metrics.git
git clone https://github.com/decentraland/dcl-quests-api-spec.git
git clone https://github.com/decentraland/dcl-scene-writer.git
git clone https://github.com/decentraland/dcl-sprites.git
git clone https://github.com/decentraland/dcl-viper.git
git clone https://github.com/decentraland/dcl-voice.git
git clone https://github.com/decentraland/dcl-tslint-config-standard.git
git clone https://github.com/decentraland/DCLVideoPlayer.git
git clone https://github.com/decentraland/dcl-xml.git
git clone https://github.com/decentraland/DCLVideoPlayerUnity.git
git clone https://github.com/decentraland/debug-comms.git
git clone https://github.com/decentraland/decentraform.git
git clone https://github.com/decentraland/decentraland-auth.git
git clone https://github.com/decentraland/decentraland-builder-scripts.git
git clone https://github.com/decentraland/decentraland-commons.git
git clone https://github.com/decentraland/decentraland-connect.git
git clone https://github.com/decentraland/decentraland-crypto.git
git clone https://github.com/decentraland/decentraland-crypto-fetch.git
git clone https://github.com/decentraland/decentraland-crypto-middleware.git
git clone https://github.com/decentraland/decentraland-crypto-rust.git
git clone https://github.com/decentraland/decentraland-crypto-utils.git
git clone https://github.com/decentraland/decentraland-ecs-utils.git
git clone https://github.com/decentraland/decentraland-eth.git
git clone https://github.com/decentraland/decentraland-dapps.git
git clone https://github.com/decentraland/decentraland-noise-utils.git	
git clone https://github.com/decentraland/decentraland-lists-graph.git
git clone https://github.com/decentraland/decentraland-l2-utils.git
git clone https://github.com/decentraland/decentraland-gatsby.git
git clone https://github.com/decentraland/eth-sig-util.git
git clone https://github.com/decentraland/eth-health.git
git clone https://github.com/decentraland/eth-connect.git
git clone https://github.com/decentraland/eslint-config.git
git clone https://github.com/decentraland/es5-context.git
git clone https://github.com/decentraland/erc721.git
git clone https://github.com/decentraland/ephemeralkey.git
git clone https://github.com/decentraland/editor-sdk7-scene-template.git
git clone https://github.com/decentraland/editor-sdk7.git
git clone https://github.com/decentraland/editor-sdk6.git
git clone https://github.com/decentraland/ecs-types.git
git clone https://github.com/decentraland/ecs-reference.git
git clone https://github.com/decentraland/ecs-math.git
git clone https://github.com/decentraland/ea-bff.git
git clone https://github.com/decentraland/dummy-token.git
git clone https://github.com/decentraland/documentation-theme.git
git clone https://github.com/decentraland/dynamic-ui.git
git clone https://github.com/decentraland/documentation.git
git clone https://github.com/decentraland/districts.git
git clone https://github.com/decentraland/discoverability.git
git clone https://github.com/decentraland/deployments-to-sqs.git
git clone https://github.com/decentraland/deeplink-landing.git
git clone https://github.com/decentraland/deployment-map.git
git clone https://github.com/decentraland/deployments-sse.git
git clone https://github.com/decentraland/DecentralandUnityPlugin.git
git clone https://github.com/decentraland/decentraland-ui-utils.git
git clone https://github.com/decentraland/decentraland-transactions.git
git clone https://github.com/decentraland/decentraland-substreams.git
git clone https://github.com/decentraland/decentraland-server.git
git clone https://github.com/decentraland/decentraland-npc-utils.git
git clone https://github.com/decentraland/jekyll-json-feed.git
git clone https://github.com/decentraland/jekyll-feed.git
git clone https://github.com/decentraland/isomorphic-form-data.git
git clone https://github.com/decentraland/ion-sfu.git
git clone https://github.com/decentraland/ion-sdk-js.git
git clone https://github.com/decentraland/intercom-chat-page.git
git clone https://github.com/decentraland/holodeck.git
git clone https://github.com/decentraland/hexutil.git
git clone https://github.com/decentraland/hashing.git
git clone https://github.com/decentraland/hammurabi.git
git clone https://github.com/decentraland/graph-node.git
git clone https://github.com/decentraland/governance-ui.git
git clone https://github.com/decentraland/governance.git
git clone https://github.com/decentraland/godot-explorer-android-template.git
git clone https://github.com/decentraland/godot-explorer.git
git clone https://github.com/decentraland/godot-docker-builder.git
git clone https://github.com/decentraland/gltf-pipeline.git
git clone https://github.com/decentraland/gate.git
git clone https://github.com/decentraland/FFMPEGMediaDecoder.git
git clone https://github.com/decentraland/ffmpeg-static.git
git clone https://github.com/decentraland/fashion-week.git
git clone https://github.com/decentraland/explorer-website.git
git clone https://github.com/decentraland/explorer-skyboxes.git
git clone https://github.com/decentraland/explorer-desktop-launcher.git
git clone https://github.com/decentraland/explorer-desktop.git
git clone https://github.com/decentraland/events.git
git clone https://github.com/decentraland/ethereumjs-util.git
git clone https://github.com/decentraland/ethereum-blocks.git
git clone https://github.com/decentraland/ethalarm.git
git clone https://github.com/decentraland/glTFast.git
git clone https://github.com/decentraland/js-sdk-toolchain.git
git clone https://github.com/decentraland/kernel-interface.git
git clone https://github.com/decentraland/l2-airdrop.git
git clone https://github.com/decentraland/lamb2.git
git clone https://github.com/decentraland/land.git
git clone https://github.com/decentraland/land-auction.git
git clone https://github.com/decentraland/land-balance-register.git
git clone https://github.com/decentraland/LAND-permissions-graph.git
git clone https://github.com/decentraland/ledger-wallet-provider.git
git clone https://github.com/decentraland/linker-dapp.git
git clone https://github.com/decentraland/linker-server.git
git clone https://github.com/decentraland/linker-server-authorizations.git
git clone https://github.com/decentraland/livekit-adapter.git
git clone https://github.com/decentraland/livekit-components-js.git
git clone https://github.com/decentraland/lods-generator.git
git clone https://github.com/decentraland/mana.git
git clone https://github.com/decentraland/MANA-community-fund-learning-content.git
git clone https://github.com/decentraland/mana-graph.git
git clone https://github.com/decentraland/marketplace.git
git clone https://github.com/decentraland/marketplace-adapter.git
git clone https://github.com/decentraland/marketplace-contracts.git
git clone https://github.com/decentraland/marketplace-favorites-server.git
git clone https://github.com/decentraland/marketplace-legacy.git
git clone https://github.com/decentraland/marketplace-server.git
git clone https://github.com/decentraland/matchmaking-server.git
git clone https://github.com/decentraland/matrix-client.git
git clone https://github.com/decentraland/matrix-playbook.git
git clone https://github.com/decentraland/matrix-reloaded.git
git clone https://github.com/decentraland/meet.git
git clone https://github.com/decentraland/livekit-rust-sdks.git
git clone https://github.com/decentraland/messaging-service.git
git clone https://github.com/decentraland/mini-comms.git
git clone https://github.com/decentraland/mini-rpc.git
git clone https://github.com/decentraland/monaco-typescript.git
git clone https://github.com/decentraland/MultiSigWallet.git
git clone https://github.com/decentraland/nats-test.git
git clone https://github.com/decentraland/nats-tools.git
git clone https://github.com/decentraland/nft-schema.git
git clone https://github.com/decentraland/nft-server.git
git clone https://github.com/decentraland/nft_bazl.git
git clone https://github.com/decentraland/nifty-gg.git
git clone https://github.com/decentraland/node-runtime.git
git clone https://github.com/decentraland/notifications-workers.git
git clone https://github.com/decentraland/notificator.git
git clone https://github.com/decentraland/offchain-marketplace-contract.git
git clone https://github.com/decentraland/opscli.git
git clone https://github.com/decentraland/ownership-server.git
git clone https://github.com/decentraland/ownership-server-owner.git
git clone https://github.com/decentraland/pass-through.git
git clone https://github.com/decentraland/pickup-quest-scene.git
git clone https://github.com/decentraland/pixel-chain-mural-scene.git
git clone https://github.com/decentraland/places.git
git clone https://github.com/decentraland/platform-actions.git
git clone https://github.com/decentraland/platform-crypto-middleware.git
git clone https://github.com/decentraland/platform-server-commons.git
git clone https://github.com/decentraland/platform-substreams-indexer.git
git clone https://github.com/decentraland/platform-test-helpers.git
git clone https://github.com/decentraland/plaza-asian.git
git clone https://github.com/decentraland/plaza-genesis.git
git clone https://github.com/decentraland/poap-ui.git
git clone https://github.com/decentraland/posix.git
git clone https://github.com/decentraland/pow-authorization-server.git
git clone https://github.com/decentraland/profile.git
git clone https://github.com/decentraland/profile-images.git
git clone https://github.com/decentraland/protoc-gen-csharp.git
git clone https://github.com/decentraland/protoc-gen-dcl.git
git clone https://github.com/decentraland/protoc-gen-rust.git
git clone https://github.com/decentraland/protocol.git
git clone https://github.com/decentraland/protocol-squad.git
git clone https://github.com/decentraland/protocol-squad-unity-explorer.git
git clone https://github.com/decentraland/provider-engine.git
git clone https://github.com/decentraland/quests.git
git clone https://github.com/decentraland/quests-client.git
git clone https://github.com/decentraland/quests-designer.git
git clone https://github.com/decentraland/quests-manager.git
git clone https://github.com/decentraland/quickjs-emscripten.git
git clone https://github.com/decentraland/rca.git
git clone https://github.com/decentraland/realm-provider.git
git clone https://github.com/decentraland/redux-persistence.git
git clone https://github.com/decentraland/redux-persistence-engine-localstorage.git
git clone https://github.com/decentraland/reels.git
git clone https://github.com/decentraland/renderer-bff.git
git clone https://github.com/decentraland/renderer-protocol.git
git clone https://github.com/decentraland/rendezvous.git
git clone https://github.com/decentraland/rentals-contract.git
git clone https://github.com/decentraland/rentals-graph.git
git clone https://github.com/decentraland/reshaper-pre-commit-hook.git
git clone https://github.com/decentraland/roads.git
git clone https://github.com/decentraland/rpc-csharp.git
git clone https://github.com/decentraland/rpc.git
git clone https://github.com/decentraland/rpc-server-benchmarker.git
git clone https://github.com/decentraland/rust-ffmpeg.git
git clone https://github.com/decentraland/rust-ffmpeg-sys.git
git clone https://github.com/decentraland/scene-explorer-tests.git
git clone https://github.com/decentraland/scene-lod-entities-manifest-builder.git
git clone https://github.com/decentraland/scene-runtime.git
git clone https://github.com/decentraland/scene-state-server.git
git clone https://github.com/decentraland/schemas.git
git clone https://github.com/decentraland/sdk.git
git clone https://github.com/decentraland/sdk-content-server.git
git clone https://github.com/decentraland/sdk-dcl-cast-scene.git
git clone https://github.com/decentraland/sdk-empty-scene-template.git
git clone https://github.com/decentraland/sdk-library.git
git clone https://github.com/decentraland/sdk-playground.git
git clone https://github.com/decentraland/sdk-test-scenes.git
git clone https://github.com/decentraland/sdk-ws.git
git clone https://github.com/decentraland/sdk6-adaption-layer.git
git clone https://github.com/decentraland/sdk7-goerli-plaza.git
git clone https://github.com/decentraland/sdk7-library-template.git
git clone https://github.com/decentraland/sdk7-scene-template.git
git clone https://github.com/decentraland/sdk7-streaming-world.git
git clone https://github.com/decentraland/sdk7-test-scenes.git
git clone https://github.com/decentraland/rpc-rust.git
git clone https://github.com/decentraland/sdk7-utils.git
git clone https://github.com/decentraland/serverless-snapshots.git
git clone https://github.com/decentraland/set-rollout-action.git
git clone https://github.com/decentraland/sfu-test.git
git clone https://github.com/decentraland/show-management.git
git clone https://github.com/decentraland/signatures-server.git
git clone https://github.com/decentraland/single-sign-on.git
git clone https://github.com/decentraland/single-sign-on-client.git
git clone https://github.com/decentraland/smart-contract-audits.git
git clone https://github.com/decentraland/smart-item-sample.git
git clone https://github.com/decentraland/smart-items.git
git clone https://github.com/decentraland/smart-wearable-sample.git
git clone https://github.com/decentraland/snapshot-server.git
git clone https://github.com/decentraland/snapshot-spaces.git
git clone https://github.com/decentraland/snapshot-strategies.git
git clone https://github.com/decentraland/snapshot.js.git
git clone https://github.com/decentraland/snapshots-fetcher.git
git clone https://github.com/decentraland/social-client.git
git clone https://github.com/decentraland/social-rpc-client-js.git
git clone https://github.com/decentraland/social-service.git
git clone https://github.com/decentraland/social-service-api-specs.git
git clone https://github.com/decentraland/social-service-ea.git
git clone https://github.com/decentraland/status-page.git
git clone https://github.com/decentraland/stoneage-browser.git
git clone https://github.com/decentraland/studios.git
git clone https://github.com/decentraland/substreams-reorg-handler.git
git clone https://github.com/decentraland/substreams-server.git
git clone https://github.com/decentraland/substreams-sink-postgres.git
git clone https://github.com/decentraland/substreams-sink-postgres-fork.git
git clone https://github.com/decentraland/subtitle.js.git
git clone https://github.com/decentraland/summit-24.git
git clone https://github.com/decentraland/synapse-identity-server.git
git clone https://github.com/decentraland/talent-hub.git
git clone https://github.com/decentraland/tap-coingecko.git
git clone https://github.com/decentraland/tap-decentraland-api.git
git clone https://github.com/decentraland/tap-decentraland-crashbot.git
git clone https://github.com/decentraland/tap-decentraland-thegraph.git
git clone https://github.com/decentraland/tap-geoip.git
git clone https://github.com/decentraland/tap-lever.git
git clone https://github.com/decentraland/tap-opensea.git
git clone https://github.com/decentraland/target-snowflake.git
git clone https://github.com/decentraland/test-new-ecs-scene.git
git clone https://github.com/decentraland/test-scene-integration.git
git clone https://github.com/decentraland/testnet-contract-migrations.git
git clone https://github.com/decentraland/themetaversefestival.git
git clone https://github.com/decentraland/third-party-aggregator.git
git clone https://github.com/decentraland/third-party-api-resolver-example.git
git clone https://github.com/decentraland/third-party-providers-resolver.git
git clone https://github.com/decentraland/tile-map.git
git clone https://github.com/decentraland/tpr-graph.git
git clone https://github.com/decentraland/transactions-server.git
git clone https://github.com/decentraland/treasure-hunt.git
git clone https://github.com/decentraland/ts-proto.git
git clone https://github.com/decentraland/ui.git
git clone https://github.com/decentraland/ui-env.git
git clone https://github.com/decentraland/unity-builder.git
git clone https://github.com/decentraland/unity-exercise-battle.git
git clone https://github.com/decentraland/unity-exercise-effects.git
git clone https://github.com/decentraland/unity-explorer.git
git clone https://github.com/decentraland/unity-explorer-plugin-system.git
git clone https://github.com/decentraland/Unity-GifDecoder.git
git clone https://github.com/decentraland/unity-gltf.git
git clone https://github.com/decentraland/unity-jsb.git
git clone https://github.com/decentraland/unity-renderer.git
git clone https://github.com/decentraland/unity-return-license.git
git clone https://github.com/decentraland/unity-shared-dependencies.git
git clone https://github.com/decentraland/unity-social-client.git
git clone https://github.com/decentraland/yellowpaper
git clone https://github.com/decentraland/ws-room-service.git
git clone https://github.com/decentraland/worlds-content-server.git
git clone https://github.com/decentraland/world.git
git clone https://github.com/decentraland/whitelist-sale.git
git clone https://github.com/decentraland/webrtc-broker.git
git clone https://github.com/decentraland/webgl-ime-input.git
git clone https://github.com/decentraland/web.git
git clone https://github.com/decentraland/wearables-contracts.git
git clone https://github.com/decentraland/wearable-preview.git
git clone https://github.com/decentraland/watermelon.git
git clone https://github.com/decentraland/wasm-quickjs-loader.git
git clone https://github.com/decentraland/warp-server-with-rpc-server.git
git clone https://github.com/decentraland/Vtubing.git
git clone https://github.com/decentraland/vr-client.git
git clone https://github.com/decentraland/voting.git
git clone https://github.com/decentraland/vorpal.git
git clone https://github.com/decentraland/vestings-builder.git
git clone https://github.com/decentraland/vesting-dashboard.git
git clone https://github.com/decentraland/uws-test.git
git clone https://github.com/decentraland/urn-resolver.git
git clone https://github.com/decentraland/urn-namespaces.git
git clone https://github.com/decentraland/UniVRM.git
git clone https://github.com/decentraland/UnityGLTF.git
git clone https://github.com/decentraland/Unity3D-NSubstitute.git
git clone https://github.com/decentraland/ViveMediaDecoder.git
